app/routes/main.py
from flask import Flask, Blueprint, render_template, flash, get_flashed_messages, redirect, url_for, request, abort
from flask_login import login_required, current_user
from app.forms import CreateListForm, EditListName, AddAdditionalListItems, AddManyListItems
from app.models import List, Item, User

main_bp = Blueprint("main", __name__)

@main_bp.route('/', methods=['GET'])
def index():
    return render_template('/main/index.html')

@main_bp.route('/profile', methods=['GET'])
@login_required
def profile():
    return render_template('/main/profile.html', lists=List().return_all_lists(current_user.get_username()))

@main_bp.route('/u/<username>', methods=['GET'])
def public_profile(username):
    if not User().custom_query('username', username):
        return redirect(url_for('main.index'))
    return render_template('/main/public-profile.html', lists=List().explore_lists(), user=username)

@main_bp.route('/explore', methods=['GET'])
def explore():
    return render_template('/main/explore.html', lists=List().explore_lists())


@main_bp.route('/create-list', methods=['GET'])
def create_list():
    return render_template('/main/create-list.html', form=CreateListForm(), message=get_flashed_messages())

@main_bp.route('/add/list', methods=['POST'])
def add_list():
    form = CreateListForm()
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('main.create_list'))
    

    add = List(name=request.form.get('list_name'), user=current_user.get_username(), explore=request.form.get('exploreable'), link_code=List.generate_link_code()).add_list(request.form.get('list_items'))
    
    return redirect(url_for('main.list_page', user=current_user.get_username(), link_code=add))

@main_bp.route('/u/<user>/<link_code>', methods=['GET'])
def list_page(user, link_code):
    query = List().query_list(user, link_code)
    if not query:
        return abort(404)
    return render_template('/main/view-list.html', user=user, list=query, edit=EditListName(), add=AddAdditionalListItems(), many=AddManyListItems())

@main_bp.route('/edit/list/name/<code>', methods=['POST'])
def edit_list_title(code):
    if not current_user.is_authenticated:
        return abort(404)
    if not List().update_list_title(current_user.get_username(), code, request.form.get('list_name')):
        return abort(404)
    
    return redirect(url_for('main.list_page', user=current_user.get_username(), link_code=code))

@main_bp.route('/edit/list/add/item/<code>/<id>', methods=['POST'])
def add_list_item(code, id):
    if (not current_user.is_authenticated) or (not List().check_correct_user(current_user.get_username(), code)):
        return abort(404)
    if not Item(item=request.form.get('list_item'), list_id=id).add_item():
        return 'Something went wrong'

    return redirect(url_for('main.list_page', user=current_user.get_username(), link_code=code))

@main_bp.route('/edit/list/add/many/items/<code>/<id>', methods=['POST'])
def add_many_list_items(code, id):
    if (not current_user.is_authenticated) or (not List().check_correct_user(current_user.get_username(), code)):
        return abort(404)

    Item(list_id=id).add_many(request.form.get('list_items'))

    return redirect(url_for('main.list_page', user=current_user.get_username(), link_code=code))

@main_bp.route('/edit/list/delete/item/<code>/<list_id>/<item>', methods=['GET'])
def delete_list_item(code, list_id, item):
    if (not current_user.is_authenticated) or (not List().check_correct_user(current_user.get_username(), code)):
        return abort(404)
    if not Item().delete_item(list_id, item):
        return ('', 400)
    return ('', 204)
    
    
@main_bp.route('/add/starred/list', methods=['GET'])
def add_star():
    pass

@main_bp.route('/remove/starred/list', methods=['GET'])
def remove_star():
    pass
    

app/templates/main/create-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'include/styles.html' %}
    <title>Create a new list - ListyShare</title>
</head>
<body>
    {% if current_user.is_authenticated %}
        {% include 'include/navigation/navigation-logged-in.html' %}
    {% else %}
        {% include 'include/navigation/navigation-logged-out.html' %}
    {% endif %}
    <main>
        {% if not current_user.is_authenticated %}
            <div class="login-required">
                <h1>Getting Started</h1>
                <p class="login-required-p">
                    In order to create a list, you must sign in. Feel free to login or create an account to create a list.
                </p>
                <a href="{{url_for('auth.login')}}">
                    <button type="button" class="btn-blue">Sign in</button>
                </a>
                <a href="{{url_for('auth.register')}}">
                    <button type="button" class="btn-blue">Register</button>
                </a>
            </div>
        
        {% else %}
            {% if message != [] %}
                    <div class="flashed-message">{{message[0] | replace('[', '') | replace(']', '') | replace("'", '') }} </div>
            {% endif %}
            <h1></h1>
            <div class="create-list-form">
                <form method="POST" action="/add/list">
                    {{form.list_name(placeholder="List name", class="list-name-input")}}
                    <p class="create-list-p">This is the name of the list. It must be unique to your other lists. List name cannot exceed 60 characters.                    </p>
                    {{form.list_items(placeholder="Write or paste your list here. Each line is a list item", class="list-items-textarea")}}
                    <p class="create-list-p">
                        Enter your list items. Each line is a list item. You'll be able to edit these later.
                    </p>
                   <div class="explore-checkbox">
                    {{form.exploreable(id="explore-checkbox")}}
                    <h4>Searchable</h4>
                   </div>
                   <p class="create-list-p">
                    Searchable determines if a list is discoverable through our explore section. Regardless if a list is set to searchable or not, the list will be accessible via URL.
                    </p>
                    
                    {{form.csrf_token}}

                    <button type="submit" class="btn-blue">Create List</button>
                    
                </form>
            </div>
        
        {% endif %}

        
    </main>
</body>
</html>

app/templates/main/explore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'include/styles.html' %}
    <title>ListyShare - Explore</title>
</head>
<body>
    {% if current_user.is_authenticated %}
        {% include 'include/navigation/navigation-logged-in.html' %}
    {% else %}
        {% include 'include/navigation/navigation-logged-out.html' %}
    {% endif %}
    <main>
        <div class="explore-wrapper">
            <h2 id="explore-heading">
                Explore our most popular lists
            </h2>
            <div class="explore-lists">
                {% for item in lists %}
                    <div class="explore-block">
                            <h3 class="explore-list-name">
                                <a href="{{url_for('main.list_page', user=item.user, link_code=item.link_code)}}">
                                    {{item.name}}
                                </a>
                            </h3>
                            {% if current_user.is_authenticated %}
                                {% if current_user.get_username()|title == item.user|title %}
                                    <h5 class="explore-by">By <span class="list-by"><a href="{{url_for('main.profile')}}">{{item.user}}</span></a></h5>
                                {% else %}
                                    <h5 class="explore-by">By <span class="list-by"><a href="{{url_for('main.public_profile', username=item.user)}}">{{item.user}}</span></a></h5>
                                {% endif %}
                            
                            {% else %}
                                <h5 class="explore-by">By <span class="list-by"><a href="{{url_for('main.public_profile', username=item.user)}}">{{item.user}}</span></a></h5>
                            {% endif %}
                            <h4 class="exploreable">Explorable</h4>
                    </div>
                {% endfor %}

            </div>
        </div>
    </main>
</body>
</html>

app/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'include/styles.html' %}
    <title>ListyShare</title>
</head>
<body>
    {% include 'include/navigation/navigation-logged-out.html' %}
    <main>
        <div class="index-top-section">
            <h1>Create lists to share<br> with everyone</h1>
            <div class="top-section-buttons">
                <a href="{{url_for('main.create_list')}}">
                    <button type="button" class="btn-blue">Try it out</button>
                </a>
                <a href="{{url_for('main.explore')}}">
                    <button type="button" class="btn-blue">Explore</button>
                </a>
            </div>
        </div>

        <div class="features">
            
        </div>
    </main>
</body>
</html>

app/templates/main/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'include/styles.html' %}
    <title>ListyShare</title>
</head>
<body>
    {% include 'include/navigation/navigation-logged-in.html' %}
    <main>
        <div class="profile-wrapper">
            <div class="profile-info">
                <h1 id="profile-username">{{current_user.get_username()}}</h1>
            </div>

            <div class="profile-split">
                <div class="profile-left">
                    <h3 id="your-lists-profile">
                        Your Lists
                    </h3>
                    {% for item in lists %}
                        <div class="profile-list">
                                <h3><a href="{{url_for('main.list_page', user=current_user.get_username(), link_code=item.link_code)}}">{{item.name}}</h3></a>
                            {% if item.explore == 'y' %}
                                <h4 class="exploreable">Explorable</h4>
                            {% else %}
                                <h4 class="exploreable">Not Exporable</h4>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <dib class="profile-right">
                    Starred Lists
                </dib>
            </div>
        </div>
    </main>
</body>
</html>

app/templates/main/public-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'include/styles.html' %}
    <title>ListyShare - {{user}}</title>
</head>
<body>
    {% include 'include/navigation/navigation-logged-in.html' %}
    <main>
        <div class="profile-wrapper">
            <div class="profile-info">
                <h1 id="profile-username">{{user|title}}</h1>
            </div>

            <div class="profile-split">
                <div class="profile-left">
                    <h3 id="your-lists-profile">
                        {{user|title}}'s Lists
                    </h3>
                    {% for item in lists %}
                        <div class="profile-list">
                                <h3><a href="{{url_for('main.list_page', user=user, link_code=item.link_code)}}">{{item.name}}</h3></a>
                            {% if item.explore == 'y' %}
                                <h4 class="exploreable">Explorable</h4>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <dib class="profile-right">
                    Starred Lists
                </dib>
            </div>
        </div>
    </main>
</body>
</html>

app/templates/main/view-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'include/styles.html' %}
    <title>Create a new list - ListyShare</title>
</head>
<body>
    {% if current_user.is_authenticated %}
        {% include 'include/navigation/navigation-logged-in.html' %}
    {% else %}
        {% include 'include/navigation/navigation-logged-out.html' %}
    {% endif %}
    <main>
        <!-- If Username matches the username of the list, show list with edit features-->
            {% if current_user.is_authenticated %}
                {% if current_user.get_username() == user %}
                    <div class="view-list-wrapper">
                        <div class="view-list-top-bar">
                            <div class="view-list-top-left">
                                <h3 onclick="editListName()" class="list-title">{{list.name}} <span class="edit-list-title"><img id="edit-svg" height="13" width="13" src="{{url_for('static', filename='images/svg/edit.svg')}}">Edit</span></h3>
                                <h5>By <span class="list-by"><a href="{{url_for('main.profile')}}">{{user}}</a></span></h5>
                                {% if list.explore == 'y' %}
                                    <h4 class="exploreable">Explorable</h4>
                                {% endif %}
                            </div>
                            
                            <div class="view-list-top-right">
                                <input type="text" value="https://127.0.0.1:/{{list.link_code}}">
                            </div>

                            <div class="view-list-edit-title">
                                <form method="POST" action="/edit/list/name/{{list.link_code}}">
                                    <div class="form-control">
                                        {{edit.list_name(class="list-name-input", value=list.name)}}
                                        {{edit.csrf_token}}
                                        <button type="submit" class="form-btn">Save</button>
                                        <button type="button" class="form-btn" onclick="cancelNameChange()">Cancel</button>
                                    </div>
                                
                                </form>
                            </div>
                        </div>

                        <div class="view-list">
                            <h5>List</h5>
                        </div>

                        <div class="list-items">
                            {% for item in list.items %}
                                <div class="list-item-block" id="list-item-block-{{item.id}}">
                                    <p class="looped-list-item">{{item.item}}</p>
                                    <a onclick="deleteListItem('{{list.link_code}}', '{{list.id}}', '{{item.id}}')">
                                        <img src="{{url_for('static', filename='images/svg/delete.svg')}}" height="20" width="20" class="svg-delete">
                                    </a>
                                </div>
                            {% endfor %}
                        </div>

                        <div class="view-list-add-items">
                            <div class="add-item-form">
                                <form method="POST" action="/edit/list/add/item/{{list.link_code}}/{{list.id}}">
                                    <div class="form-control" id="new-item-form">
                                        {{add.list_item(class="list-name-input", placeholder="Enter your new list item")}}
                                        <button type="submit" class="form-btn">Add Item</button>
                                        <button type="button" onclick="cancelListItem()" class="form-btn">Cancel</button>
                                    </div>
                                
                                </form>
                            </div>
                            <div class="add-multiple-items-form">
                                <form method="POST" action="/edit/list/add/many/items/{{list.link_code}}/{{list.id}}">
                                    {{many.list_items(class="list-items-textarea", placeholder="Write or paste your list here. Each line is a list item")}}
                                    <button type="submit" class="form-btn">Add Items</button>
                                    <button type="button" class="form-btn" onclick="cancelMultipleListItems()">Cancel</button>
                                </form>
                            </div>
                            <div class="add-items-btns">
                                <button type="button" onclick="addListItem('{{list.id}}')" class="form-btn">Add Item</button>
                                <button type="button" onclick="addManyItems()" class="form-btn">Add Many Items</button>
                            </div>
                        </div>
                    </div>
                
                {% endif %}

                {% else %}
                    <div class="view-list-wrapper">
                        <div class="view-list-top-bar">
                            <div class="view-list-top-left">
                                <h3 class="list-title">{{list.name}}</h3>
                                <h5>By <span class="list-by"><a href="{{url_for('main.public_profile', username=user)}}">{{user}}</a></span></h5>
                                {% if list.exploreable == 'None' %}
                                    <h4 class="not-exploreable">Not Explorable</h4>
                                {% else %}
                                    <h4 class="exploreable">Explorable</h4>
                                {% endif %}
                            </div>
                            
                            <div class="view-list-top-right">
                                <input type="text" value="https://127.0.0.1:/{{list.link_code}}">
                            </div>
                        </div>

                        <div class="view-list">
                            <h5>List</h5>
                        </div>

                        <div class="list-items">
                            {% for item in list.items %}
                                <p class="looped-list-item">{{item.item}}</p>
                            {% endfor %}
                        </div>


                    </div>
                {% endif %}
            
            
            
            
            <!-- Else just show the list with shareable options -->
            
            {% else %}
                <div class="view-list-wrapper">
                    <div class="view-list-top-bar">
                        <div class="view-list-top-left">
                            <h3 class="list-title">{{list.name}}</h3>
                            <h5>By <span class="list-by"><a href="{{url_for('main.public_profile', username=user)}}">{{user}}</a></span></h5>
                            {% if list.exploreable == 'None' %}
                                <h4 class="not-exploreable">Not Explorable</h4>
                            {% else %}
                                <h4 class="exploreable">Explorable</h4>
                            {% endif %}
                        </div>
                        
                        <div class="view-list-top-right">
                            <input type="text" value="https://127.0.0.1:/{{list.link_code}}">
                        </div>
                    </div>

                    <div class="view-list">
                        <h5>List</h5>
                    </div>

                    <div class="list-items">
                        {% for item in list.items %}
                            <p class="looped-list-item">{{item.item}}</p>
                        {% endfor %}
                    </div>


                </div>
            {% endif %}
        
    </main>
    {% include 'include/scripts.html' %}
</body>
</html>